name: 'Git FTP Sync'
description: 'Deploy and delete files on FTP server based on Git changes'
inputs:
  ftp_host:
    description: 'FTP host'
    required: true
  ftp_user:
    description: 'FTP user'
    required: true
  ftp_pass:
    description: 'FTP password'
    required: true
  branch:
    description: 'Branch name'
    required: true
  before_sha:
    description: 'Previous commit SHA'
    required: true
  after_sha:
    description: 'Current commit SHA'
    required: true
  extract_path:
    description: 'Path to extract files on the FTP server'
    required: false
    default: '/'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ftp_host=${{ inputs.ftp_host }}
    - ftp_user=${{ inputs.ftp_user }}
    - ftp_pass=${{ inputs.ftp_pass }}
    - branch=${{ inputs.branch }}
    - before_sha=${{ inputs.before_sha }}
    - after_sha=${{ inputs.after_sha }}
    - extract_path=${{ inputs.extract_path }}
branding:
  color: 'red'
  icon: 'upload-cloud'