name: 'Git FTP Sync'
description: 'Deploy and delete files on FTP server based on Git changes'
inputs:
  ftp_host:
    description: 'FTP host'
    required: true
  ftp_user:
    description: 'FTP user'
    required: true
  ftp_pass:
    description: 'FTP password'
    required: true
  branch:
    description: 'Branch name'
    required: true
  extract_path:
    description: 'Path to extract files on the FTP server'
    required: false
    default: '/'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'
  args:
    - ${{ inputs.ftp_host }}
    - ${{ inputs.ftp_user }}
    - ${{ inputs.ftp_pass }}
    - ${{ inputs.branch }}
    - ${{ inputs.extract_path }}
branding:
  color: 'red'
  icon: 'upload-cloud'